package com.svhelloworld.knotlog.messages;


/**
 * A message generated by vessel instrumentation. Typically
 * a NMEA0183 or NMEA2000 message. Can also be a user generated
 * "marker" message.
 * 
 * @author Jason Andersen
 * @since Feb 13, 2010
 *
 */
@Deprecated
public interface InstrumentMessage extends VesselMessage {
    /**
     * @return the source of the message
     */
    public VesselMessageSource getSource();
}
