package com.svhelloworld.knotlog.messages;

/**
 * Defines the source of a instrument message.
 * 
 * @author Jason Andersen
 * @since Feb 16, 2010
 *
 */
public enum VesselMessageSource {
    /**
     * message received in NMEA0183 protocol
     */
    NMEA0183,
    /**
     * message received in NMEA2000 protocol
     */
    NMEA2000,
    /**
     * message received in GPX protocol
     */
    GPX,
    /**
     * a message generated by this application, such as a marker message
     */
    APPLICATION
}
