package com.svhelloworld.knotlog.messages;

import java.util.Date;

import com.svhelloworld.knotlog.i18n.Localizable;

/**
 * The basic message generated by a vessel.
 * 
 * @author Jason Andersen
 * @since Feb 13, 2010
 *
 */
public interface VesselMessage extends Localizable, Comparable<VesselMessage> {
    /**
     * @return the name of this type of message
     */
    public String getName();
    /**
     * @return a user readable description of this message's contents
     */
    public String getDisplayMessage();
    /**
     * @return timestamp of the message in zulu (UTC) time
     */
    public Date getTimestamp();
    /**
     * @param timestamp new timestamp value
     */
    public void setTimestamp(Date timestamp);
    /**
     * @return the source of the message
     */
    public VesselMessageSource getSource();
}
